config/routes.rb
Rails.application.routes.draw do

  resources :urls
  match "/riot.txt" => redirect("/assets/riot.txt"), via: [:get]
  mount ActionCable.server => '/cable'
  mount Ckeditor::Engine => '/ckeditor'

  # get "/:locale " => "home#index"
  root to: redirect("/#{I18n.locale}", status: 302), as: "i18n_root"

  scope "(:locale)", locale: /fr|en/ do

    resources :karmas
    resources :pollings
    resources :notes
    resources :wallet_histories
    resources :badges
    resources :histories
    resources :tournaments
    resources :feedbacks
    resources :mentors
    resources :search_suggestions
    resources :champions
    resources :articles
    resources :legal
    resources :plannings
    resources :whitelists
    resources :messages
    resources :discord
    # resources :home
    resources :contacts

    resources :users do
      member do
        get :user_preview
        get :avatar_modal
        put :avatar
        get :leave_search_modal
        get :leave_search
        get :edit_role_modal
        patch :edit_role
        patch :edit_state
        put :add_champion
        put :remove_champion
        put :change_language
        put :search_team
      end
    end

    resources :game_accounts do
      member do
        get :get_game_rank
        get :refresh
        get :refresh_account
        get :activate_game_account
        post :choose_game
      end
    end

    resources :teams do
      member do
        get :preview
        get :add_user
        get :remove_user
        get :leave_modal
        get :dissolution_modal
        get :listing
        get :role_collection
        post :role_collection
        get :add_role
        post :add_role
        post :change_role
        get :modify_modal
        put :modify
        put :tofit
        put :remplacement
        put :start
        put :dissolution
        get :tabs_refresh
      end
    end

    resources :games do
      member do
        put :roles
      end
    end

    resources :polls do
      member do
        get :tabs
        put :choices
      end
    end

    resources :compositions do
      member do
        put :add_champion
        put :remove_champion
        put :ratio
      end
    end

    resources :team_applications do
      member do
        get :reject
        put :answer
      end
    end

    get 'recruitment_center' => 'team_applications#recruitment_center', as: "recruitment_center"

    resources :subscription_plans do
      member do
        put :select_duration
        get :informations
        put :payment
        get :payment_response
        get :payment_result
        get :restricted_content
      end
    end

    resources :subscriptions do
      member do
        post :renewal
        put :state
      end
    end

    resources :wallets do
      member do
        get :virtual_currency
        put :manager
        get :informations
        post :payment
        get :payment_response
        get :payment_result
      end
    end

    resources :discord do
      member do
        get :team_preview
      end
    end

    resources :achievements do
      member do
        put :add_user
      end
    end

    resources :seances do
      member do
        put :validate
      end
    end

    resources :mentorats do
      member do
        get :mentorat_preview
        put :change_teacher
        put :claim
        put :stop
      end
    end

    resources :premades do
      member do
        put :leave
        put :kick
      end
    end

    resources :invitations do
      member do
        get :generate_parrainage_link
        put :accept
        put :decline
      end
    end

    resources :friendships do
      member do
        put :accept
        put :decline
        put :remove
        put :block
        put :unblock
      end
    end

    resources :votes do
      member do
        put :election
      end
    end

    resources :teamings do
      member do
        put :swap
        put :swaper
        put :swap_captain
        put :advices_validation
      end
    end

    resources :notifications do
      member do
        put :mark_as_read
        get :mark_read
      end
    end

    devise_for :users, skip: :omniauth_callbacks, :controllers => { :registrations => "users/registrations" }

    devise_scope :user do
      get "sign_up", to: "devise/registrations#new"
      get '/users/:id/password/edit', to: "devise/passwords#edit", as: "reset_pw"
      put '/update_password', to: "devise/passwords#update", as: "update_pw"
      get '/registration/edit' => 'devise/registrations#edit'
      post "/registration/create" => "users/registrations#create", as: "create_user"
      get "/password/reset" => "devise/passwords#edit"
      get "login", to: "devise/sessions#new"
      get "logout", to: "devise/sessions#destroy"
    end

=begin
    devise_for :users, skip: :omniauth_callbacks, :controllers => { registrations: "registrations" } do
      get 'users/sign_up' => 'devise/registrations#new'
      #get '/users/edit' => 'devise/registrations#edit'
    end

    devise_scope :user do
     get "sign_up", to: "devise/registrations#new"
     get "login", to: "devise/sessions#new"
     get "logout", to: "devise/sessions#destroy"
   end
=end

    get 'dashboard' => 'users#dashboard'
    get 'second_step' => 'game_accounts#second_step'
    get 'third_step' => 'users#third_step'
    get 'searching_team' => 'users#searching_team'
    get 'leave_team' => 'users#leave_team'

    get 'subscription/manager' => 'subscriptions#manager', as: 'subscriptions_manager'

    get 'about' => 'home#about'
    get 'admin_panel' => 'home#admin_panel'
    get 'codename_fifty' => 'home#code'
    get 'analytics' => 'home#analytics'
    get 'parrainages' => 'users#parrainages'
    get 'join_us' => 'home#join_us'
    get 'our_partners' => 'home#our_partners', as: 'our_partners'
    get 'our_streamers' => 'home#our_streamers', as: 'our_streamers'
    get 'our_team' => 'home#our_team', as: 'our_team'
    get 'pricing' => 'home#pricing', as: 'pricing'
    get 'pantheon' => 'home#pantheon', as: 'pantheon'
    get 'profil'  => 'home#profil_user_type'
    get 'unsubscribe' => 'home#unsubscribe', as: 'unsubscribe'
    get 'eula' => 'legal#eula', as: 'eula'
    get 'cgu' => 'legal#cgu', as: 'cgu'

    scope '/wallets', :controller => :wallets do
      post :notification
    end

    get 'index.php/joueurs-lol' => 'home#old_page'
    get 'index.php/joueurs-ow' => 'home#old_page'
    get 'index.php' => 'home#old_page'
    get '/index.php/*path' => 'home#old_page'
    get '/components/*path' => 'home#old_page'
    get '/images/*path' => 'home#old_page'
    get '/administrator/*path' => 'home#old_page'
    get '/modules/*path' => 'home#old_page'

    get 'team_builder' => 'teams#team_builder'

    post 'analytics_search', :to => 'home#analytics_search', :as => 'analytics_search'

    get 'contact' => 'contacts#new'

    root to: "home#index"

  end

  get '/:short_url', to: 'urls#show'

end

app/models/composition.rb
class Composition < ApplicationRecord
  belongs_to :team
  has_many :notes

  self.per_page = 25
end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController
  before_action :set_composition, except: [:index, :new, :create]
  before_action :set_champions, only: [:add_champion, :remove_champion, :ratio]
  respond_to :js

  def index
    authorize! :manage, :all
    @compositions = Composition.all.paginate(:page => params[:page])
  end

  def new
    @team = Team.find(params[:team])
    @composition = Composition.new
    respond_to do |format|
      format.html { redirect_to @team, alert: "Une erreur est survenue lors de l'ouverture de la fenêtre de création de composition."}
      format.js
    end
  end

  def create
    @team = Team.find(params[:team])
    @composition = Composition.new(composition_params)
    @composition.team_id = params[:team]
    @composition.picks = Array.new(@composition.team.game.nb_players, nil)
    @composition.bans = [nil, nil, nil]
    # Partial variables
    @champions = Champion.where(game_id:@team.game_id).pluck(:name)
    @composition.save
    respond_to do |format|
      format.html { redirect_to @team, notice: "Composition créée avec succès." }
      format.js
    end
  end

  def add_champion
    num_champ = params[:num_champ].to_i
    champion = params[:champion].downcase
    if params[:type] == "pick"
      @composition.picks[num_champ] = champion
    elsif params[:type] == "ban"
      @composition.bans[num_champ] = champion
    end
    @composition.save
  end

  def remove_champion
    num_champ = params[:num_champ].to_i
    if params[:type] == "pick"
      @composition.picks[num_champ] = nil
    elsif params[:type] == "ban"
      @composition.bans[num_champ] = nil
    end
    @composition.save
  end

  def ratio
    if params[:type] == "win-up"
      @composition.win += 1
    elsif params[:type] == "win-down"
      @composition.win -= 1
    elsif params[:type] == "lose-up"
      @composition.lose += 1
    elsif params[:type] == "lose-down"
      @composition.lose -= 1
    end
    @composition.save
  end

  def edit
  end

  def update
    @composition.update(composition_params)
  end

  def destroy
    @team = @composition.team
    if @composition.destroy
      redirect_to compositions_path, notice: "Composition supprimée avec succès."
    else
      redirect_to compositions_path, alert: "Une erreur s'est produite."
    end
  end

  private

  def set_composition
    @composition = Composition.find(params[:id])
  end

  def set_champions
    @champions = Champion.where(game_id:@composition.team.game_id).pluck(:name)
  end

  def composition_params
    params.require(:composition).permit(:title)
  end
end

app/helpers/compositions_helper.rb
module CompositionsHelper
end

app/views/compositions/_composition.html.erb
<% @composition = composition %>
<% @team = composition.team %>
<% if @composition.win > @composition.lose
  @panel = "panel-success"
elsif @composition.win == @composition.lose
  @panel = "panel-warning"
elsif @composition.win < @composition.lose
  @panel = "panel-danger"
end %>
<% nb = @team.game.nb_players %>
<div class="panel <%= @panel %>" style="margin-bottom:30px;">
  <div id="compo-<%= @composition.id %>-header" class="panel-heading text-center">
    <div class="row">
      <div class="col-xs-10">
        <h4><%= @composition.title %></h4>
      </div>
      <div class="col-xs-2 text-right" style="padding-top:5px;">
        <%= link_to "<i class='fa fa-pencil-square-o'></i>".html_safe, edit_composition_path(@composition), method: :get, remote: true, style:"color:inherit;"%>
        <% if captain? %>
          | <%= link_to "<i class='fa fa-remove'></i>".html_safe, @composition, method: :delete, remote: true, data:{confirm: "Voulez-vous supprimer cette composition?"}, style:"color:inherit;"%>
        <% end %>
      </div>
    </div>
  </div>
  <div class="panel-body compo-body">
    <div class="row">
      <div class="col-sm-9">
        <div class="row text-center">
          <% for i in 0..(nb -1) %>
            <% pick = @composition.picks[i] %>
            <div class="col-xs-2" style="padding:10px;">
              <% if !pick.nil? %>
                <!-- Show champion icon -->
                <%= link_to '<i class="fa fa-remove"></i>'.html_safe, remove_champion_composition_path(@composition, num_champ:i, type:"pick"), method: :put, remote: true %>
                <% if !Champion.where(name:pick).first.nil? %>
                  <div style="display:inline-block;" data-toggle="tooltip" title="<%= pick.capitalize %>">
                    <%= image_tag Champion.where(name:pick).first.icon, style:"width:50px;" %>
                  </div>
                <% else %>
                  <%= pick.capitalize %>
                <% end %>
              <% else %>
                <div style="display:inline-block" data-toggle="tooltip" title="<%=t 'compositions.tooltip' %>">
                  <input type="text" class="form-control" style="text-transform:lowercase" placeholder="Pick <%= i+1 %>" id="pick-<%= i %>-<%= @composition.id %>">
                </div>
                <script type="text/javascript">
                  var names = <%= raw @champions.to_json %>;
                  $('#pick-<%= i %>-<%= @composition.id %>').autocomplete({
                    source : names,
                    select: function(event, ui){ // lors de la sélection d'une proposition
                     $.ajax({
                      type: "PUT",
                      url: "/compositions/<%= @composition.id %>/add_champion" + "?champion=" + ui.item.value + "&num_champ=<%= i %>" + "&type=pick"
                     });
                    }
                  });
                </script>
              <% end %>
            </div>
          <% end %>
        </div>
        <% if @team.game.compo_bans == true %>
        <hr>
        <div class="col-sm-12 text-center">
          <% for i in 0..4 %>
            <% ban = @composition.bans[i] %>
            <div class="col-xs-2">
              <% if !ban.nil? %>
                <!-- Show champion icon -->
                <%= link_to '<i class="fa fa-remove"></i>'.html_safe, remove_champion_composition_path(@composition, num_champ:i, type:"ban"), method: :put, remote: true %>
                <% if !Champion.where(name:ban).first.nil? %>
                  <div style="display:inline-block;" data-toggle="tooltip" title="<%= ban.capitalize %>">
                    <%= image_tag Champion.where(name:ban).first.icon, style:"width:50px;" %>
                  </div>
                <% else %>
                  <%= ban.capitalize %>
                <% end %>
              <% else %>
                <div style="display:inline-block" data-toggle="tooltip" title="<%=t 'compositions.tooltip' %>">
                  <input type="text" class="form-control" style="text-transform:lowercase" placeholder="Ban <%= i+1 %>" id="ban-<%= i %>-<%= @composition.id %>">
                </div>
                <script type="text/javascript">
                  var names = <%= raw @champions.to_json %>;
                  $('#ban-<%= i %>-<%= @composition.id %>').autocomplete({
                    source : names,
                    select: function(event, ui){ // lors de la sélection d'une proposition
                     $.ajax({
                      type: "PUT",
                      url: "/compositions/<%= @composition.id %>/add_champion" + "?champion=" + ui.item.value + "&num_champ=<%= i %>" + "&type=ban"
                     });
                    }
                  });
                </script>
              <% end %>
            </div>
          <% end %>
        </div>
        <% end %>
      </div>
      <div class="col-sm-3">
        <div id="compo-ratio" class="text-center">
          <h4><%=t 'polls.results' %></h4>
          <div class="row">
            <div class="col-xs-6">
              <div class="col-xs-4">
                <%= link_to "<i class='fa fa-chevron-up'></i>".html_safe, ratio_composition_path(@composition, type:"win-up"), method: :put, remote: true, style:"color:black;display:block;" %>
                <%= link_to "<i class='fa fa-chevron-down'></i>".html_safe, ratio_composition_path(@composition, type:"win-down"), method: :put, remote: true, style:"color:black;display:block;" %>
              </div>
              <div class="col-xs-8" style="color:#93c47d;">
                <h4 style="text-shadow:0 1px 2px rgba(0, 0, 0, 0.5); font-size: 30px;margin-top:0px;"><%= @composition.win %></h4>
                <b><%=t 'layout.victories' %></b>
              </div>
            </div>
            <div class="col-xs-6">
              <div class="col-xs-8" style="color:#e06666;">
                <h4 style="text-shadow:0 1px 2px rgba(0, 0, 0, 0.5); font-size: 30px;margin-top:0px;"><%= @composition.lose %></h4>
                <b><%=t 'layout.defeats' %></b>
              </div>
              <div class="col-xs-4">
                <%= link_to "<i class='fa fa-chevron-up'></i>".html_safe, ratio_composition_path(@composition, type:"lose-up"), method: :put, remote: true, style:"color:black;display:block;" %>
                <%= link_to "<i class='fa fa-chevron-down'></i>".html_safe, ratio_composition_path(@composition, type:"lose-down"), method: :put, remote: true, style:"color:black;display:block;" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <div id="notes-compo-<%= @composition.id %>">
    <% @composition.notes.order('created_at desc').each do |note| %>
      <div class="row note-row" id="note-<%= note.id %>">
        <%= render(note) %>
      </div>
    <% end %>
  </div>
  <div style="padding:10px;">
    <%= simple_form_for(Note.new, remote: true) do |f| %>
      <%= hidden_field_tag(:composition, @composition.id) %>
      <div class="input-group">
        <input type="text" class="form-control" placeholder="<%=t 'compositions.comment' %>" name="note[body]" id="note_body_<%= @composition.id %>" maxlength="500" autocomplete="off">
        <span class="input-group-btn">
          <%= button_tag(type: "submit", class: "btn btn-default", style:"padding:5px 12px;") do %>
             <i class="fa fa-plus"></i>
          <% end %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/compositions/_compositions.html.erb
<% @team.compositions.order('win desc').each do |composition| %>
  <div id="compo-<%= composition.id %>">
    <%= render(composition) %>
  </div>
<% end %>

app/views/compositions/_edit.html.erb
<%= simple_form_for(@composition, method: :put, remote: true) do |f| %>
  <input type="text" value="<%= @composition.title %>" class="form-control" style="text-align:center;" name="composition[title]" id="composition_title" maxlength="45" autofocus>
<% end %>

app/views/compositions/_new.html.erb
<%= simple_form_for(@composition, remote: true) do |f| %>
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h3 class="modal-title text-center" id="myModalLabel"><%=t 'compositions.new' %></h3>
    </div>
    <div class="modal-body text-center">
      <h4><%=t 'layout.title' %></h4>
      <input type="text" class="form-control" style="text-align:center;width:90%;margin:0 auto;" name="composition[title]" id="composition_title" maxlength="45" autofocus>
      <%= hidden_field_tag "team", params[:team] %>
    </div>
    <div class="modal-footer" style="text-align:center;">
      <%= submit_tag "#{t 'btn.create'}", class: "btn btn-primary"%>
      <button type="button" class="btn btn-default" data-dismiss="modal"><%=t 'btn.close' %></button>
    </div>
  </div>
</div>
<% end %>

app/views/compositions/add_champion.js.erb
$('#compo-<%= @composition.id %>').html("<%= j render(@composition) %>");

app/views/compositions/create.js.erb
$('#compos').html("<%= j (render 'compositions/compositions') %>");
$("#compos").scrollTop($("#compos")[0].scrollHeight);
// $('#compos').prepend('<%= j render(@composition) %>');
$("#modal-window").modal('hide');

app/views/compositions/destroy.js.erb
$('#compos').html("<%= j (render 'compositions/compositions') %>");

app/views/compositions/edit.js.erb
$('#compo-<%= @composition.id %>-header').html("<%= j (render 'compositions/edit') %>");

app/views/compositions/index.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Compositions</h3>
    </div>
    <div class="panel-body">
      <table class="table">
        <thead>
          <tr>
            <th>Titre</th>
            <th>Equipe</th>
            <% for i in 1..6 %>
            <th>Pick <%= i %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
        <% @compositions.order('created_at desc').each do |composition| %>
          <tr>
            <td><%= composition.title %></td>
            <td><%= link_to composition.team.name, composition.team %></td>
            <% composition.picks.each do |pick| %>
              <td><%= pick %></td>
            <% end %>
            <td><%= link_to "<i class='fa fa-remove'></i>".html_safe, composition, method: :delete, data: {confirm: "Etes-vous sûr de vouloir supprimer cette composition ?"} %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="panel-footer">
      <div class="row">
        <div class="col-sm-3" style="margin-top:10px;">
          <%= link_to "Retour", admin_panel_path, class:"btn btn-default" %>
        </div>
        <div class="col-sm-6 text-center">
          <%= will_paginate @compositions, :previous_label => "Précédent", :next_label => "Suivant", inner_window: 2, outer_window: 1 %>
        </div>
        <div class="col-sm-3"></div>
      </div>
    </div>
  </div>
</div>

app/views/compositions/new.js.erb
$("#modal-window").modal('show');
$("#modal-window").html("<%= j (render 'compositions/new') %>");

app/views/compositions/ratio.js.erb
$('#compo-<%= @composition.id %>').html("<%= j render(@composition) %>");

app/views/compositions/remove_champion.js.erb
$('#compo-<%= @composition.id %>').html("<%= j render(@composition) %>");

app/views/compositions/update.js.erb
$('#compo-<%= @composition.id %>').html("<%= j render(@composition) %>");