config/routes.rb
Rails.application.routes.draw do

  resources :urls
  match "/riot.txt" => redirect("/assets/riot.txt"), via: [:get]
  mount ActionCable.server => '/cable'
  mount Ckeditor::Engine => '/ckeditor'

  # get "/:locale " => "home#index"
  root to: redirect("/#{I18n.locale}", status: 302), as: "i18n_root"

  scope "(:locale)", locale: /fr|en/ do

    resources :karmas
    resources :pollings
    resources :notes
    resources :wallet_histories
    resources :badges
    resources :histories
    resources :tournaments
    resources :feedbacks
    resources :mentors
    resources :search_suggestions
    resources :champions
    resources :articles
    resources :legal
    resources :plannings
    resources :whitelists
    resources :messages
    resources :discord
    # resources :home
    resources :contacts

    resources :users do
      member do
        get :user_preview
        get :avatar_modal
        put :avatar
        get :leave_search_modal
        get :leave_search
        get :edit_role_modal
        patch :edit_role
        patch :edit_state
        put :add_champion
        put :remove_champion
        put :change_language
        put :search_team
      end
    end

    resources :game_accounts do
      member do
        get :get_game_rank
        get :refresh
        get :refresh_account
        get :activate_game_account
        post :choose_game
      end
    end

    resources :teams do
      member do
        get :preview
        get :add_user
        get :remove_user
        get :leave_modal
        get :dissolution_modal
        get :listing
        get :role_collection
        post :role_collection
        get :add_role
        post :add_role
        post :change_role
        get :modify_modal
        put :modify
        put :tofit
        put :remplacement
        put :start
        put :dissolution
        get :tabs_refresh
      end
    end

    resources :games do
      member do
        put :roles
      end
    end

    resources :polls do
      member do
        get :tabs
        put :choices
      end
    end

    resources :compositions do
      member do
        put :add_champion
        put :remove_champion
        put :ratio
      end
    end

    resources :team_applications do
      member do
        get :reject
        put :answer
      end
    end

    get 'recruitment_center' => 'team_applications#recruitment_center', as: "recruitment_center"

    resources :subscription_plans do
      member do
        put :select_duration
        get :informations
        put :payment
        get :payment_response
        get :payment_result
        get :restricted_content
      end
    end

    resources :subscriptions do
      member do
        post :renewal
        put :state
      end
    end

    resources :wallets do
      member do
        get :virtual_currency
        put :manager
        get :informations
        post :payment
        get :payment_response
        get :payment_result
      end
    end

    resources :discord do
      member do
        get :team_preview
      end
    end

    resources :achievements do
      member do
        put :add_user
      end
    end

    resources :seances do
      member do
        put :validate
      end
    end

    resources :mentorats do
      member do
        get :mentorat_preview
        put :change_teacher
        put :claim
        put :stop
      end
    end

    resources :premades do
      member do
        put :leave
        put :kick
      end
    end

    resources :invitations do
      member do
        get :generate_parrainage_link
        put :accept
        put :decline
      end
    end

    resources :friendships do
      member do
        put :accept
        put :decline
        put :remove
        put :block
        put :unblock
      end
    end

    resources :votes do
      member do
        put :election
      end
    end

    resources :teamings do
      member do
        put :swap
        put :swaper
        put :swap_captain
        put :advices_validation
      end
    end

    resources :notifications do
      member do
        put :mark_as_read
        get :mark_read
      end
    end

    devise_for :users, skip: :omniauth_callbacks, :controllers => { :registrations => "users/registrations" }

    devise_scope :user do
      get "sign_up", to: "devise/registrations#new"
      get '/users/:id/password/edit', to: "devise/passwords#edit", as: "reset_pw"
      put '/update_password', to: "devise/passwords#update", as: "update_pw"
      get '/registration/edit' => 'devise/registrations#edit'
      post "/registration/create" => "users/registrations#create", as: "create_user"
      get "/password/reset" => "devise/passwords#edit"
      get "login", to: "devise/sessions#new"
      get "logout", to: "devise/sessions#destroy"
    end

=begin
    devise_for :users, skip: :omniauth_callbacks, :controllers => { registrations: "registrations" } do
      get 'users/sign_up' => 'devise/registrations#new'
      #get '/users/edit' => 'devise/registrations#edit'
    end

    devise_scope :user do
     get "sign_up", to: "devise/registrations#new"
     get "login", to: "devise/sessions#new"
     get "logout", to: "devise/sessions#destroy"
   end
=end

    get 'dashboard' => 'users#dashboard'
    get 'second_step' => 'game_accounts#second_step'
    get 'third_step' => 'users#third_step'
    get 'searching_team' => 'users#searching_team'
    get 'leave_team' => 'users#leave_team'

    get 'subscription/manager' => 'subscriptions#manager', as: 'subscriptions_manager'

    get 'about' => 'home#about'
    get 'admin_panel' => 'home#admin_panel'
    get 'codename_fifty' => 'home#code'
    get 'analytics' => 'home#analytics'
    get 'parrainages' => 'users#parrainages'
    get 'join_us' => 'home#join_us'
    get 'our_partners' => 'home#our_partners', as: 'our_partners'
    get 'our_streamers' => 'home#our_streamers', as: 'our_streamers'
    get 'our_team' => 'home#our_team', as: 'our_team'
    get 'pricing' => 'home#pricing', as: 'pricing'
    get 'pantheon' => 'home#pantheon', as: 'pantheon'
    get 'profil'  => 'home#profil_user_type'
    get 'unsubscribe' => 'home#unsubscribe', as: 'unsubscribe'
    get 'eula' => 'legal#eula', as: 'eula'
    get 'cgu' => 'legal#cgu', as: 'cgu'

    scope '/wallets', :controller => :wallets do
      post :notification
    end

    get 'index.php/joueurs-lol' => 'home#old_page'
    get 'index.php/joueurs-ow' => 'home#old_page'
    get 'index.php' => 'home#old_page'
    get '/index.php/*path' => 'home#old_page'
    get '/components/*path' => 'home#old_page'
    get '/images/*path' => 'home#old_page'
    get '/administrator/*path' => 'home#old_page'
    get '/modules/*path' => 'home#old_page'

    get 'team_builder' => 'teams#team_builder'

    post 'analytics_search', :to => 'home#analytics_search', :as => 'analytics_search'

    get 'contact' => 'contacts#new'

    root to: "home#index"

  end

  get '/:short_url', to: 'urls#show'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
require 'date'
#c'est ici que les pages non liées à un model sont créees

def index
=begin
    if user_signed_in?
      redirect_to dashboard_path and return
    end
=end
end

def profil_user_type
end

def contact
end

def about
end

def join_us
end

def our_partners
end

def our_streamers
end

def our_team
end

def pricing
end

def pantheon
end

def unsubscribe
  if params[:email].present?
    @user = User.find_by_email(params[:email].to_s)
    @user.unsubscribe = true
    @user.save
  end
end

def old_page
	redirect_to root_path
end

def admin_panel
	unless can? :manage, Article
		redirect_to root_path, alert: 'Vous n\'avez pas accès à ce contenu.'
	end

  @users = User.all
  @teams = Team.where.not(start_date: nil)
  @teamings = Teaming.joins(:user, :team).where.not(:teams => {start_date:nil})
end

def codename_fifty
end

def analytics
  unless can? :manage, Article
    redirect_to root_path, alert: 'Vous n\'avez pas accès à ce contenu.'
  end

  @start_date = Date.parse("2017-04-15")
  @end_date = Date.today
  @users = User.where('users.created_at BETWEEN ? AND ?', @start_date, @end_date)

  @teams = Team.where.not(start_date: nil).where('start_date BETWEEN ? AND ?', @start_date, @end_date)

  @lol_accounts = GameAccount.where(:game_id => 1).where.not(:p_role => nil)
  @ow_accounts = GameAccount.where(:game_id => 2)

  @age_min = User.maximum(:birth_date).find_age
  @age_max = User.minimum(:birth_date).find_age


  @insc_total = @users.count
  @insc_rech = @users.where(:state => 1).count
  @insc_team = @users.where(:state => 2).count
  @insc_off = @users.where(:state => 0).count
  @lol = @users.joins(:game_accounts).merge(GameAccount.where(:active => true, :game_id => 1))
  @lol_total = @lol.count
  @lol_rech = @lol.where(:state => 1).count
  @lol_team = @lol.where(:state => 2).count
  @lol_off = @lol.where(:state => 0).count
  @ow = @users.joins(:game_accounts).merge(GameAccount.where(:active => true, :game_id => 2))
  @ow_total = @ow.count
  @ow_rech = @ow.where(:state => 1).count
  @ow_team = @ow.where(:state => 2).count
  @ow_off = @ow.where(:state => 0).count

end

def analytics_search

  unless can? :manage, Article
    redirect_to root_path, alert: 'Vous n\'avez pas accès à ce contenu.'
  end

  #Date Picked
  if params[:start_date].blank?
    @start_date = Date.parse("2017-03-09")
  else
    @start_date = Date.parse(params[:start_date]).to_s
  end

  if params[:end_date].blank?
    @end_date = Date.today
  else
     @end_date = Date.parse(params[:end_date]).end_of_day.to_s
  end

  if params[:age_min].blank?
    @age_min = User.maximum(:birth_date).find_age
  else
    @age_min = params[:age_min]
  end
  @year_max = @age_min.to_i.years.ago

  if params[:age_max].blank?
    @age_max = User.minimum(:birth_date).find_age
  else
    @age_max = params[:age_max]
  end
  @year_min = @age_max.to_i.years.ago

  @users = User.where('users.created_at BETWEEN ? AND ? ', @start_date, @end_date)
  @users = @users.where('birth_date BETWEEN ? AND ? ', @year_min, @year_max)

  @teams = Team.where.not(start_date: nil).where('start_date > ?', @start_date)

  @lol_accounts = GameAccount.where(:game_id => 1)#.where.not(:p_role => nil)
  @ow_accounts = GameAccount.where(:game_id => 2)

  @insc_total = @users.count
  @insc_rech = @users.where(:state => 1).count
  @insc_team = @users.where(:state => 2).count
  @insc_off = @users.where(:state => 0).count
  @lol = @users.joins(:game_accounts).merge(GameAccount.where(:active => true, :game_id => 1))
  @lol_total = @lol.count
  @lol_rech = @lol.where(:state => 1).count
  @lol_team = @lol.where(:state => 2).count
  @lol_off = @lol.where(:state => 0).count
  @ow = @users.joins(:game_accounts).merge(GameAccount.where(:active => true, :game_id => 2))
  @ow_total = @ow.count
  @ow_rech = @ow.where(:state => 1).count
  @ow_team = @ow.where(:state => 2).count
  @ow_off = @ow.where(:state => 0).count

  respond_to do |format|
    format.js{}
  end
end


end

app/helpers/home_helper.rb
module HomeHelper
	#si tu aimes te servir des helper lâche toi, j'en ai pas encore l'habitude perso
end

app/views/home/_donateurs.html.erb
<h3><i class="fa fa-heart"></i> <%=t 'home.donators' %> <i class="fa fa-heart"></i></h3>
<p style="margin:25px;"><%=t 'home.donators_subtitle' %></p>
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6" style="margin:0 auto;">
    <table class="table table-striped">
      <tbody>
        <tr>
          <td><h4>300€</h4></td>
          <td>Pohu</td>
        </tr>
        <tr>
          <td><h4>30€</h4></td>
          <td>Abs NoLimiT</td>
        </tr>
        <tr>
          <td><h4>20€</h4></td>
          <td>Phenrig</td>
        </tr>
        <tr>
          <td><h4>20€</h4></td>
          <td>TwiiTeK</td>
        </tr>
        <tr>
          <td><h4>12€</h4></td>
          <td>Fun Fight n Fire</td>
        </tr>
        <tr>
          <td><h4>10€</h4></td>
          <td>BasseTiens</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-sm-3"></div>
</div>
<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=J96K2C8RD2EFW" class="btn btn-primary"><%=t 'home.donation' %></a>

app/views/home/_premiums.html.erb
<h3><i class="ra ra-queen-crown"></i> <%=t 'home.conquerors' %> <i class="ra ra-queen-crown"></i></h3>
<p style="margin:25px;">Prepare for Glory !</p>
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6" style="margin:0 auto;">
    <table class="table table-striped">
      <tbody>
        <tr>
          <td><b>Pohu</b></td>
          <td><%=t 'home.1st' %> <a href="#"><%=t 'home.conqueror' %></a></td>
        </tr>
        <tr>
          <td><b>Althime</b></td>
          <td><%=t 'home.2nd' %> <a href="#"><%=t 'home.conqueror' %></a></td>
        </tr>
        <tr>
          <td><b>BluePhoeniix</b></td>
          <td><%=t 'home.3rd' %> <a href="#"><%=t 'home.conqueror' %></a></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-sm-3"></div>
</div>
<hr>
<h3><i class="ra ra-tower"></i> <%=t 'home.pioniers' %> <i class="ra ra-tower"></i></h3>
<p style="margin:25px;">Prepare for Battle !</p>
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6" style="margin:0 auto;">
    <table class="table table-striped">
      <tbody>
        <tr>
          <td><b>GMB Gunner</b></td>
          <td>1er <a href="#"><%=t 'home.pionier' %></a></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-sm-3"></div>
</div>

app/views/home/about.html.erb
<style type="text/css">

	.image{

		min-width: 375px;
		min-height: 225px;
		margin: 10px;
		border-radius: 4px;

	}

</style>

<section class="container" style="display: flex; flex-wrap: wrap;">

<!--
<div class="image"><%= link_to image_tag("ourTeam.jpg", :size => "375x225"), our_team_path %></div>
<div class="image"><%= link_to image_tag("ourPartners.jpg", :size => "375x225"), our_partners_path %></div>
<div class="image"><%= link_to image_tag("ourStreamers.jpg", :size => "375x225"), our_streamers_path %></div>
<div class="image"><%= link_to image_tag("joinUs.jpg", :size => "375x225"), join_us_path %></div>
-->

<div class="panel panel-default">
	<div class="panel-body">
		<p>Vous vous trouver actuellement sur la version alpha de la nouvelle plateforme Arena Esport. Il est donc tout à fait possible que vous rencontriez des bugs, et seules un nombre limité de fonctionalités sont déjà implémentées. Si vous rencontrez le moindre problème, ou que vous avez la moindre idée d'amélioration, merci de contacter <a href="#">enzo@arena-esport.com</a> / <b>[Staff] Enzo</b> sur <a href="https://discord.gg/JvvHnvr">Discord </a>.</p>
	</div>
</div>

</section>

app/views/home/admin_panel.html.erb
<style type="text/css">
  .icon-menu .panel i { font-size: 60px; }
  .icon-menu .panel { height: 150px; text-align: center; padding: 50px 0px;}
</style>

<section class="container">

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="text-center">Admin panel</h3>
    </div>
    <div class="panel-body" style="padding:50px 10px;min-height:400px;">
      <div style="margin-bottom:50px;">
        <!-- ROW STAT 1 -->
        <div class="row">
          <div class="col-sm-4">
            <div class="box-stat">
              <div class="col-xs-4 stat-left">
                <i class="fa fa-user"></i>
              </div>
              <div class="col-xs-8 stat-right">
                <%= @users.count %> (+ <%= @users.where(created_at: Time.now.beginning_of_week-7.days..Time.now.end_of_week-7.days).count %>)
              </div>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="box-stat">
              <div class="col-xs-4 stat-left">
                <i class="fa fa-group"></i>
              </div>
              <div class="col-xs-8 stat-right">
                <%= @teams.count %> (+ <%= @teams.where(created_at: Time.now.beginning_of_week-7.days..Time.now.end_of_week-7.days).count %>)
              </div>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="box-stat">
              <div class="col-xs-4 stat-left">
                <i class="fa fa-list"></i>
              </div>
              <div class="col-xs-8 stat-right">
                <%= @teamings.count %> (+ <%= @teamings.where(created_at: Time.now.beginning_of_week-7.days..Time.now.end_of_week-7.days).count %>)
              </div>
            </div>
        </div>
      </div>
      <div style="padding:30px;margin:30px 0px;">
        <!-- ROW 1 -->
        <div class="row icon-menu">
          <div class="col-sm-2">
            <a href="<%= users_path %>">
              <div class="panel">
                <i class="fa fa-user"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-2">
            <a href="<%= teams_path %>">
              <div class="panel">
                <i class="fa fa-group"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-2">
            <a href="<%= teamings_path %>">
              <div class="panel">
                <i class="fa fa-list"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-2">
            <a href="<%= premades_path %>">
              <div class="panel">
                <i class="fa fa-handshake-o"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-2">
            <a href="<%= parrainages_path %>">
              <div class="panel">
                <i class="fa fa-user-plus"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-2">
            <a href="<%= team_applications_path %>">
              <div class="panel">
                <i class="fa fa-pencil-square-o"></i>
              </div>
            </a>
          </div>
        </div>
        <!-- ROW 2 -->
        <div class="row icon-menu">
          <div class="col-sm-2">
            <a href="<%= messages_path %>">
              <div class="panel">
                <i class="fa fa-envelope"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-2">
            <a href="<%= karmas_path %>">
              <div class="panel">
                <i class="fa fa-thumbs-up"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-2">
            <a href="<%= polls_path %>">
              <div class="panel">
                <i class="fa fa-check-square-o"></i>
              </div>
            </a>
          </div>
          <% if can? :manage, :all %>
          <div class="col-sm-2">
            <a href="<%= subscription_plans_path %>">
              <div class="panel">
                <i class="fa fa-shopping-cart"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-2">
            <a href="<%= subscriptions_path %>">
              <div class="panel">
                <i class="fa fa-credit-card"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-2">
            <a href="<%= achievements_path %>">
              <div class="panel">
                <i class="ra ra-scroll-unfurled"></i>
              </div>
            </a>
          </div>
          <% end %>
        </div>

        <% if can? :manage, :all %>
        <!-- ROW 3 -->
        <div class="row icon-menu">
          <div class="col-sm-2">
            <a href="<%= games_path %>">
              <div class="panel">
                <i class="fa fa-gamepad"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-2">
            <a href="<%= tournaments_path %>">
              <div class="panel">
                <i class="fa fa-trophy"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-2">
            <a href="<%= champions_path %>">
              <div class="panel">
                <i class="ra ra-helmet"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-2">
            <a href="<%= compositions_path %>">
              <div class="panel">
                <i class="fa fa-cubes"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-2">
            <a href="<%= notes_path %>">
              <div class="panel">
                <i class="fa fa-pencil-square"></i>
              </div>
            </a>
          </div>
          <div class="col-sm-2">
            <a href="<%= badges_path %>">
              <div class="panel">
                <i class="ra ra-castle-flag"></i>
              </div>
            </a>
          </div>
        </div>

        <!-- ROW 4 -->
        <div class="row icon-menu">
          <div class="col-sm-2">
            <a href="/analytics">
              <div class="panel">
                <i class="fa fa-line-chart"></i>
              </div>
            </a>
          </div>
        </div>
        <% end %>

      </div>

    </div> <!-- End icon menu part -->
  </div>
</div>
</section>

app/views/home/analytics_search.js.erb
$('.fa-refresh').hide();

$('#insc_total').html("<%=@insc_total%>");
$('#insc_rech').html("<%=@insc_rech%>");
$('#insc_team').html("<%=@insc_team%>");
$('#insc_off').html("<%=@insc_off%>");

$('#lol_total').html("<%=@lol_total%>");
$('#lol_rech').html("<%=@lol_rech%>");
$('#lol_team').html("<%=@lol_team%>");
$('#lol_off').html("<%=@lol_off%>");

$('#ow_total').html("<%=@ow_total%>");
$('#ow_rech').html("<%=@ow_rech%>");
$('#ow_team').html("<%=@ow_team%>");
$('#ow_off').html("<%=@ow_off%>");

app/views/home/index.html.erb
<style type="text/css">
  section {
    padding-top: 100px;
    padding-bottom: 100px;
  }

</style>
    <!-- Header -->
    <header>
        <div class="container">
            <div class="intro-text">
                <div class="intro-heading line-1 anim-typewriter"><%=t('home.title')%></div>
                <div class="intro-lead-in"><%=t 'home.subtitle' %></div>
                <% if !user_signed_in? %>
                  <%= link_to "#{t 'btn.signup'}", sign_up_path, class: "btn btn-xl" %>
                <% else %>
                  <%= link_to "Dashboard", dashboard_path, class: "btn btn-xl" %>
                <% end %>
                <!--<a href="#services" class="page-scroll btn btn-xl">Fonctionnement</a>
                <a href="#formules" class="page-scroll btn btn-xl">Nos formules</a>-->
            </div>
        </div>
    </header>

    <!-- Services Section -->
    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading"><%=t 'home.3steps_title' %></h2>
                    <h3 class="section-subheading text-muted"><%=t 'home.3steps_subtitle' %></h3>
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-id-card fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="service-heading"><%=t 'home.step1_title' %></h4>
                    <p class="text-muted"><%=t 'home.step1_content' %></p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="service-heading"><%=t 'home.step2_title' %></h4>
                    <p class="text-muted"><%=t 'home.step2_content' %></p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-users fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="service-heading"><%=t 'home.step3_title' %></h4>
                    <p class="text-muted"><%=t 'home.step3_content' %></p>
                </div>
            </div>
        </div>
    </section>

    <section id="testimonials" class="bg-red" style="padding-top:50px;padding-bottom:50px;">
      <%= render partial: 'home/references_carousel'%>
    </section>

app/views/home/our_streamers.html.erb
<section>
	Nos streamers.
</section>

app/views/home/pricing.html.erb
<style type="text/css">
section { padding-top: 50px; padding-bottom: 50px; }
</style>

<div class="container" style="margin-bottom:100px;position:relative;z-index:10">
	<div class="row text-center">
		<div class="col-sm-4">
			<img src="<%= asset_url("assets/pricing/Free.png") %>" class="img-responsive img-centered">
			<div class="heading-box" style="margin-bottom:50px;">
				<h2><%=t 'subscriptions.free_title' %></h2>
				<h3 class="subheading"><%=t 'subscriptions.free_subtitle' %></h3>
			</div>
			<h3><%=t 'subscriptions.unlimited' %></h3>
			<br>
			<% unless user_signed_in? %>
				<a href="/users/sign_up" class="btn btn-primary btn-lg btn-block"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> <%=t 'teams.apply_for' %></a>
			<% else %>
				<a href="#" class="btn btn-primary btn-lg btn-block" disabled><i class="fa fa-pencil-square-o" aria-hidden="true"></i> <%=t 'teams.apply_for' %></a>
			<% end %>
		</div>
		<div class="col-sm-8">
			<div class="row">
				<div class="col-sm-6">
					<img src="<%= asset_url("assets/pricing/Month.png") %>" class="img-responsive img-centered">
				</div>
				<div class="col-sm-6">
					<img src="<%= asset_url("assets/pricing/Lifetime.png") %>" class="img-responsive img-centered">
				</div>
			</div>
			<div class="heading-box">
				<h2><%=t 'subscriptions.premium_title' %></h2>
				<h3 class="subheading"><%=t 'subscriptions.premium_subtitle' %></h3>
			</div>
			<div class="row">
				<div class="col-sm-6">
					<h3>1 <%=t 'layout.month' %></h3>
					<br>
					<a href="<%= subscription_plan_path(id:2) %>" class="btn btn-primary btn-lg btn-block"><i class="fa fa-search-plus" aria-hidden="true"></i> <%=t 'btn.see_more' %></a>
				</div>
				<div class="col-sm-6">
					<h3><%=t 'subscriptions.lifetime' %> !</h3>
					<br>
					<a href="<%= subscription_plan_path(id:3) %>" class="btn btn-primary btn-lg btn-block"><i class="fa fa-search-plus" aria-hidden="true"></i> <%=t 'btn.see_more' %></a>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/home/unsubscribe.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Notifications Email</h3>
    </div>
    <div class="panel-body" style="min-height:200px;padding:100px 20px;">
      <% if params[:email].present? && !@user.nil? %>
        <div class="alert alert-success text-center">Vous avez été correctement désinscrit des notifications par mail.</div>
      <% else %>
        <div class="alert alert-danger text-center">Email non reconnu, merci de contacter un administrateur en utilisant la fenêtre de discussion en bas à droite de votre écran.</div>
      <% end %>
    </div>
  </div>
</div>