config/routes.rb
Rails.application.routes.draw do

  resources :urls
  match "/riot.txt" => redirect("/assets/riot.txt"), via: [:get]
  mount ActionCable.server => '/cable'
  mount Ckeditor::Engine => '/ckeditor'

  # get "/:locale " => "home#index"
  root to: redirect("/#{I18n.locale}", status: 302), as: "i18n_root"

  scope "(:locale)", locale: /fr|en/ do

    resources :karmas
    resources :pollings
    resources :notes
    resources :wallet_histories
    resources :badges
    resources :histories
    resources :tournaments
    resources :feedbacks
    resources :mentors
    resources :search_suggestions
    resources :champions
    resources :articles
    resources :legal
    resources :plannings
    resources :whitelists
    resources :messages
    resources :discord
    # resources :home
    resources :contacts

    resources :users do
      member do
        get :user_preview
        get :avatar_modal
        put :avatar
        get :leave_search_modal
        get :leave_search
        get :edit_role_modal
        patch :edit_role
        patch :edit_state
        put :add_champion
        put :remove_champion
        put :change_language
        put :search_team
      end
    end

    resources :game_accounts do
      member do
        get :get_game_rank
        get :refresh
        get :refresh_account
        get :activate_game_account
        post :choose_game
      end
    end

    resources :teams do
      member do
        get :preview
        get :add_user
        get :remove_user
        get :leave_modal
        get :dissolution_modal
        get :listing
        get :role_collection
        post :role_collection
        get :add_role
        post :add_role
        post :change_role
        get :modify_modal
        put :modify
        put :tofit
        put :remplacement
        put :start
        put :dissolution
        get :tabs_refresh
      end
    end

    resources :games do
      member do
        put :roles
      end
    end

    resources :polls do
      member do
        get :tabs
        put :choices
      end
    end

    resources :compositions do
      member do
        put :add_champion
        put :remove_champion
        put :ratio
      end
    end

    resources :team_applications do
      member do
        get :reject
        put :answer
      end
    end

    get 'recruitment_center' => 'team_applications#recruitment_center', as: "recruitment_center"

    resources :subscription_plans do
      member do
        put :select_duration
        get :informations
        put :payment
        get :payment_response
        get :payment_result
        get :restricted_content
      end
    end

    resources :subscriptions do
      member do
        post :renewal
        put :state
      end
    end

    resources :wallets do
      member do
        get :virtual_currency
        put :manager
        get :informations
        post :payment
        get :payment_response
        get :payment_result
      end
    end

    resources :discord do
      member do
        get :team_preview
      end
    end

    resources :achievements do
      member do
        put :add_user
      end
    end

    resources :seances do
      member do
        put :validate
      end
    end

    resources :mentorats do
      member do
        get :mentorat_preview
        put :change_teacher
        put :claim
        put :stop
      end
    end

    resources :premades do
      member do
        put :leave
        put :kick
      end
    end

    resources :invitations do
      member do
        get :generate_parrainage_link
        put :accept
        put :decline
      end
    end

    resources :friendships do
      member do
        put :accept
        put :decline
        put :remove
        put :block
        put :unblock
      end
    end

    resources :votes do
      member do
        put :election
      end
    end

    resources :teamings do
      member do
        put :swap
        put :swaper
        put :swap_captain
        put :advices_validation
      end
    end

    resources :notifications do
      member do
        put :mark_as_read
        get :mark_read
      end
    end

    devise_for :users, skip: :omniauth_callbacks, :controllers => { :registrations => "users/registrations" }

    devise_scope :user do
      get "sign_up", to: "devise/registrations#new"
      get '/users/:id/password/edit', to: "devise/passwords#edit", as: "reset_pw"
      put '/update_password', to: "devise/passwords#update", as: "update_pw"
      get '/registration/edit' => 'devise/registrations#edit'
      post "/registration/create" => "users/registrations#create", as: "create_user"
      get "/password/reset" => "devise/passwords#edit"
      get "login", to: "devise/sessions#new"
      get "logout", to: "devise/sessions#destroy"
    end

=begin
    devise_for :users, skip: :omniauth_callbacks, :controllers => { registrations: "registrations" } do
      get 'users/sign_up' => 'devise/registrations#new'
      #get '/users/edit' => 'devise/registrations#edit'
    end

    devise_scope :user do
     get "sign_up", to: "devise/registrations#new"
     get "login", to: "devise/sessions#new"
     get "logout", to: "devise/sessions#destroy"
   end
=end

    get 'dashboard' => 'users#dashboard'
    get 'second_step' => 'game_accounts#second_step'
    get 'third_step' => 'users#third_step'
    get 'searching_team' => 'users#searching_team'
    get 'leave_team' => 'users#leave_team'

    get 'subscription/manager' => 'subscriptions#manager', as: 'subscriptions_manager'

    get 'about' => 'home#about'
    get 'admin_panel' => 'home#admin_panel'
    get 'codename_fifty' => 'home#code'
    get 'analytics' => 'home#analytics'
    get 'parrainages' => 'users#parrainages'
    get 'join_us' => 'home#join_us'
    get 'our_partners' => 'home#our_partners', as: 'our_partners'
    get 'our_streamers' => 'home#our_streamers', as: 'our_streamers'
    get 'our_team' => 'home#our_team', as: 'our_team'
    get 'pricing' => 'home#pricing', as: 'pricing'
    get 'pantheon' => 'home#pantheon', as: 'pantheon'
    get 'profil'  => 'home#profil_user_type'
    get 'unsubscribe' => 'home#unsubscribe', as: 'unsubscribe'
    get 'eula' => 'legal#eula', as: 'eula'
    get 'cgu' => 'legal#cgu', as: 'cgu'

    scope '/wallets', :controller => :wallets do
      post :notification
    end

    get 'index.php/joueurs-lol' => 'home#old_page'
    get 'index.php/joueurs-ow' => 'home#old_page'
    get 'index.php' => 'home#old_page'
    get '/index.php/*path' => 'home#old_page'
    get '/components/*path' => 'home#old_page'
    get '/images/*path' => 'home#old_page'
    get '/administrator/*path' => 'home#old_page'
    get '/modules/*path' => 'home#old_page'

    get 'team_builder' => 'teams#team_builder'

    post 'analytics_search', :to => 'home#analytics_search', :as => 'analytics_search'

    get 'contact' => 'contacts#new'

    root to: "home#index"

  end

  get '/:short_url', to: 'urls#show'

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_asker
  before_action :set_asked, except: [:create]
  before_action :set_team

  skip_before_action :verify_authenticity_token

  def index
    # 28/03 - fix rollbar item 26
    redirect_to dashboard_path, alert: "Une erreur s'est produite dans votre liste de notifications. Veuillez contacter un administrateur."
  end

  def create
    if params[:friendship].nil?
      @asked = User.find(params[:asked])
    else
      @account = GameAccount.where("replace(lower(name), ' ', '') LIKE ?", params[:friendship][:friend].downcase.gsub(/\s+/, '')).first
      unless @account.nil?
        @asked = @account.user
      else
        @asked = nil
      end
    end
    @user = @asked

    unless @asked.nil?
      unless Friendship.where(user_id: @asker.id, friend_id: @asked.id, status: 2).exists?
        unless Friendship.where(user_id: @asker.id, friend_id: @asked.id, status: 0).exists?
          unless Friendship.where(user_id: @asker.id, friend_id: @asked.id, status: 1).exists?
            Friendship.create(user_id: @asker.id, friend_id: @asked.id, status: 0)
            Friendship.create(user_id: @asked.id, friend_id: @asker.id, status: 1)
            Notification.create(recepteur: @asked, emetteur: @asker, category:"friendship", action:"request", notifiable: @asker)
          else
            @friendship1 = Friendship.where(user_id: @asker.id, friend_id: @asked.id).first
            @friendship2 = Friendship.where(user_id: @asked.id, friend_id: @asker.id).first
            @friendship1.update_attribute(:status, 2)
            @friendship2.update_attribute(:status, 2)
            Notification.create(recepteur: @asked, emetteur: @asker, category:"friendship", action:"accept", notifiable: @asker)
          end
          if params[:team].nil?
            respond_to do |format|
              format.html { redirect_to @asked, notice: "Demande d'ami envoyée." }
              format.js { flash[:friend] = "Demande d'ami envoyée." }
            end
          else
            respond_to do |format|
              format.html { redirect_to @team, notice: "Demande d'ami envoyée." }
              format.js { flash[:friend] = "Demande d'ami envoyée." }
            end
          end
        else
          respond_to do |format|
            format.js { flash[:friend] = "Demande en attente de validation." }
          end
        end
      else
        respond_to do |format|
          format.js { flash[:friend] = "Le joueur est déjà dans votre liste d'amis." }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to dashboard_path, alert: "Nom incorrect ou le joueur n'est pas inscrit sur Arena." }
        format.js { flash[:friend] = "Nom incorrect ou joueur inconnu." }
      end
    end
  end

  def accept
    @friendship1 = Friendship.where(user_id: @asker.id, friend_id: @asked.id).first
    @friendship2 = Friendship.where(user_id: @asked.id, friend_id: @asker.id).first
    @friendship1.update_attribute(:status, 2)
    @friendship2.update_attribute(:status, 2)
    Notification.create(recepteur: @asker, emetteur: @asked, category:"friendship", action:"accept", notifiable: @asked)
    check_achievements(@asker,"friendships")
    check_achievements(@asker,"friendships")
    if params[:team].nil?
      respond_to do |format|
        format.html { redirect_to @asker, notice: "Demande d'ami acceptée." }
        format.js
      end
    else
      redirect_to @team, notice: "Demande d'ami acceptée."
      return
    end
  end

  def decline
    Friendship.where(user_id: @asker.id, friend_id: @asked.id).first.destroy
    Friendship.where(user_id: @asked.id, friend_id: @asker.id).first.destroy
    if params[:team].nil?
      respond_to do |format|
        format.html { redirect_to @asker, notice: "Demande d'ami refusée." }
        format.js
      end
    else
      redirect_to @team, notice: "Demande d'ami refusée."
      return
    end
  end

  def remove
    Friendship.where(user_id: @asker.id, friend_id: @asked.id).first.destroy
    Friendship.where(user_id: @asked.id, friend_id: @asker.id).first.destroy unless Friendship.where(user: @asked.id, friend: @asker.id).first.status == 3
    if params[:team].nil?
      respond_to do |format|
        format.html { redirect_to @asked, notice: "L'utilisateur a été retiré de votre liste d'amis." }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to @team, notice: "L'utilisateur a été retiré de votre liste d'amis." }
        format.js
      end
    end
  end

  def block
    if @asker.friends.include?(@asked)
      @friendship1 = Friendship.where(user_id: @asker.id, friend_id: @asked.id).first
      @friendship2 = Friendship.where(user_id: @asked.id, friend_id: @asker.id).first.destroy unless Friendship.where(user: @asked.id, friend: @asker.id).first.status == 3
      @friendship1.update_attribute(:status, 3)
    else
      Friendship.create(user_id: @asker.id, friend_id: @asked.id, status: 3)
    end
    if params[:team].nil?
      respond_to do |format|
        format.html { redirect_to @asked, notice: "L'utilisateur a été bloqué." }
        format.js
      end
    else
      redirect_to @team, notice: "L'utilisateur a été bloqué."
      return
    end
  end

  def unblock
    Friendship.where(user_id: @asker.id, friend_id: @asked.id).first.destroy
    if params[:team].nil?
      respond_to do |format|
        format.html { redirect_to @asked, notice: "L'utilisateur a été débloqué." }
        format.js
      end
    else
      redirect_to @team, notice: "L'utilisateur a été débloqué."
      return
    end
  end

  private

  def set_team
    @team = Team.find(params[:team]) unless params[:team].nil?
  end

  def set_asker
    @asker = User.find(params[:asker])
  end

  def set_asked
    @asked = User.find(params[:asked])
    @user = @asked
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_avatar.html.erb
<% @user = user %>
<% if ((@user.can? :manage, Champion) or (@user.can? :manage, Article)) && @user.avatar.present? %>
  <%= image_tag @user.avatar.thumb.url, style:"width:50px;", class:"img-thumbnail #{"bg-gold" if (@user.can? :manage, Champion) && @user.role != "admin"} #{"bg-admin" if (@user.can? :manage, Article)}" %>
<% else %>
  <% unless @user.icon.nil? or @user.icon.empty? %>
    <%= image_tag @user.icon, style:"width:50px;", class:"img-thumbnail #{"bg-gold" if (@user.can? :manage, Champion) && @user.role != "admin"} #{"bg-admin" if (@user.can? :manage, Article)}" %>
  <% else %>
    <%= image_tag image_url('icons/icon1.jpg'), style:"width:50px;", class:"img-thumbnail #{"bg-gold" if (@user.can? :manage, Champion) && @user.role != "admin"} #{"bg-admin" if (@user.can? :manage, Article)}" %>
  <% end %>
<% end %>

app/views/friendships/_friender.html.erb
<% if current_user != @user %>
  <% if !@user.blocked_friends.include?(current_user) %>
    <% if !current_user.friends.include?(@user) %>
      <% if current_user.requested_friends.include?(@user) %>
        <%= link_to "Accepter", accept_friendship_path(asker: @user, asked: current_user), method: :put, remote: true, class:"btn btn-success" %>
        <%= link_to "Refuser", decline_friendship_path(asker: @user, asked: current_user), method: :put, remote: true, class:"btn btn-danger" %>
      <% elsif current_user.pending_friends.include?(@user) %>
        <button href="#" class="btn btn-default" disabled="disabled">Demande envoyée</button>
      <% else %>
        <% unless current_user.blocked_friends.include?(@user) %>
          <%= link_to "<i class='fa fa-user-plus'></i>".html_safe, friendships_path(asker: current_user, asked: @user), method: :post, remote: true, class:"btn btn-default", id:"request" %>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to "<i class='fa fa-user-times'></i>".html_safe, remove_friendship_path(id:1, asker: current_user, asked: @user), method: :put, remote: true, data: {confirm: "Retirer le joueur de votre liste d'amis ?"}, class:"btn btn-default", id:"requested" %>
    <% end %>
  <% else %>
    <button href="#" class="btn btn-default" disabled="disabled">Bloqué</button>
  <% end %>
<% end %>

<% if current_user != @user %>
  <% if current_user.blocked_friends.include?(@user) %>
    <%= link_to "<i class='fa fa-check-circle'></i>".html_safe, unblock_friendship_path(id:1, asker: current_user, asked: @user), method: :put, remote: true, data: {confirm: "Débloquer le joueur ?"}, class:"btn btn-default" %>
  <% else %>
    <%= link_to "<i class='fa fa-ban'></i>".html_safe, block_friendship_path(id:1, asker: current_user, asked: @user), method: :put, remote: true, data: {confirm: "Bloquer le joueur ?"}, class:"btn btn-default" %>
  <% end %>
<% end %>

app/views/friendships/_index.html.erb
<div class="dropdown-menu" id="friends-dropdown">
  <div id="friends-dropdown-heading">
    <h5 style="text-align:center; margin:0px;"><%=t 'friendships.many' %></h5>
  </div>
  <% if current_user.friends.empty? && current_user.pending_friends.empty? %>
    <p style="text-align:center;margin-top:35%;margin-bottom: 32%;"><%=t 'friendships.none' %></p>
  <% else %>
    <div style="height:75%; width:100%;overflow-x:hidden;overflow-y:scroll;">
    <ul id="friends-list" style="padding:0px; width:95%">
    <% current_user.friends.order('status desc').order('last_sign_in_at desc').each do |friend|%>
        <li id="friend-<%= friend.id %>">
          <div class="row" style="margin-left:0px;">
            <%= link_to friend do %>
            <div class="col-xs-3" style="text-align:right;">
              <%= render(partial: 'friendships/avatar', locals: {reload: true, user: friend}) %>
              <div id="status-friend-<%= friend.id %>" class="<%= friend.status == 1 ? 'status-online' : 'status-offline' %> status-dot status-avatar"></div>
            </div>
            <div class="col-xs-7" style="padding-top:5px;">
              <p>
                <b>
                  <% if friend.account.present? %>
                    <%= friend.account.name %>
                  <% else %>
                    <%= friend.user_name %>
                  <% end %>
                </b>
                <i class="explain"><%= friend.user_name %></i><br>
                <% if friend.state == 2 %>
                  <span style="color:#c0392b;"><%= truncate(friend.teamings.where(active:true).first.team.name, length: 30) %></span>
                <% elsif friend.state == 1 %>
                  <span><%=t 'friendships.state1' %></span>
                <% else %>
                  <span><%=t 'friendships.state0' %></span>
                <% end %>
              </p>
              <% if friend.status == 0 %>
                <div id="offline-<%= friend.id %>" style="">
                  <%= render partial:'friendships/last_sign_in', locals:{date:friend.last_sign_in_at} %>
                </div>
              <% end %>
            </div>
            <% end %> <!-- link to friend -->
            <% if current_user.premade.present? && current_user.premade.users.include?(friend.account) %>
              <div class="col-xs-2" style="padding-top:10px;">
                <%= link_to '<i class="fa fa-remove" aria-hidden="true"></i>'.html_safe, kick_premade_path(current_user.premade, friend: friend.id), method: :put, data: { confirm: 'Voulez-vous exclure ce joueur de la premade ?' } %>
              </div>
            <% end %>
          </div>
        </li>
    <% end %> <!-- @notifications.each -->
    <% unless current_user.pending_friends.empty? %>
      <div id="pending-friends">
        <%= render 'friendships/pending' %>
      </div>
    <% end %>
  </ul>
  </div>
  <% end %> <!-- @notifications.empty? -->
  <div id="friends-dropdown-footer" class="col-sm-12">
    <%= simple_form_for(@friendship, remote: true) do |f| %>
      <% unless current_user.account.nil?
        @game = current_user.account.game
      else
        @game = Game.find(1)
      end %>

      <div class="input-group">
        <input type="text" class="form-control" placeholder="<%=t 'layout.player' %>" name="friendship[friend]" id="friendship_friend" style="text-align:center;">
        <span class="input-group-btn">
          <button type="submit" class="btn btn-default" style="padding:5px 12px;">
            <i class='fa fa-plus'></i>
          </button>
        </span>
      </div>
    <%= hidden_field_tag(:asker, current_user.id) %>
    <% end %>
    <div id="notice-friend" class="col-sm-12">
    </div>
  </div>


</div>

app/views/friendships/_last_sign_in.html.erb
<span class="explain" style="text-transform:none;"><%=t 'friendships.offline', time_ago: time_ago_in_words(date) %></span>

app/views/friendships/_pending.html.erb
<h5 class="text-center"><%=t 'layout.pending' %></h5>
<% current_user.pending_friends.each do |pending|%>
  <li>
    <div class="row" style="margin-left:0px;">
      <div class="col-xs-3" style="text-align:right;">
        <%= render(partial: 'friendships/avatar', locals: {reload: true, user: pending}) %>
      </div>
      <div class="col-xs-9" style="padding-top:10px;">
        <b style="font-size:14px;">
          <% if pending.account.present? %>
            <%= pending.account.name %>
          <% else %>
            <%= pending.user_name %>
          <% end %>
          </b>&nbsp;&nbsp;
        <i class="explain"><%= pending.user_name %></i>
      </div>
    </div>
  </li>
<% end %>

app/views/friendships/accept.js.erb
$('#friender').html("<%= j (render(:partial => 'friendships/friender', locals: {reload: true})).html_safe %>");

app/views/friendships/block.js.erb
$('#friender').html("<%= j (render(:partial => 'friendships/friender', locals: {reload: true})).html_safe %>");

app/views/friendships/create.js.erb
$('#friendship_friend').val('');
$('#notice-friend').html("<%= flash[:friend] %>");
$('#pending-friends').html("<%= j (render 'friendships/pending') %>");
<% unless @user.nil? %>
$('#friender').html("<%= j (render(:partial => 'friendships/friender', locals: {reload: true})).html_safe %>");
<% end %>
<% unless @team.nil? %>
$('#team-tabs').html("<%= j (render 'teams/roster') %>");
<% end %>

app/views/friendships/decline.js.erb
$('#friender').html("<%= j (render(:partial => 'friendships/friender', locals: {reload: true})).html_safe %>");

app/views/friendships/remove.js.erb
$('#friender').html("<%= j (render(:partial => 'friendships/friender', locals: {reload: true})).html_safe %>");
<% unless @team.nil? %>
$('#team-tabs').html("<%= j (render 'teams/roster') %>");
<% end %>

app/views/friendships/unblock.js.erb
$('#friender').html("<%= j (render(:partial => 'friendships/friender', locals: {reload: true})).html_safe %>");