config/routes.rb
Rails.application.routes.draw do

  resources :urls
  match "/riot.txt" => redirect("/assets/riot.txt"), via: [:get]
  mount ActionCable.server => '/cable'
  mount Ckeditor::Engine => '/ckeditor'

  # get "/:locale " => "home#index"
  root to: redirect("/#{I18n.locale}", status: 302), as: "i18n_root"

  scope "(:locale)", locale: /fr|en/ do

    resources :karmas
    resources :pollings
    resources :notes
    resources :wallet_histories
    resources :badges
    resources :histories
    resources :tournaments
    resources :feedbacks
    resources :mentors
    resources :search_suggestions
    resources :champions
    resources :articles
    resources :legal
    resources :plannings
    resources :whitelists
    resources :messages
    resources :discord
    # resources :home
    resources :contacts

    resources :users do
      member do
        get :user_preview
        get :avatar_modal
        put :avatar
        get :leave_search_modal
        get :leave_search
        get :edit_role_modal
        patch :edit_role
        patch :edit_state
        put :add_champion
        put :remove_champion
        put :change_language
        put :search_team
      end
    end

    resources :game_accounts do
      member do
        get :get_game_rank
        get :refresh
        get :refresh_account
        get :activate_game_account
        post :choose_game
      end
    end

    resources :teams do
      member do
        get :preview
        get :add_user
        get :remove_user
        get :leave_modal
        get :dissolution_modal
        get :listing
        get :role_collection
        post :role_collection
        get :add_role
        post :add_role
        post :change_role
        get :modify_modal
        put :modify
        put :tofit
        put :remplacement
        put :start
        put :dissolution
        get :tabs_refresh
      end
    end

    resources :games do
      member do
        put :roles
      end
    end

    resources :polls do
      member do
        get :tabs
        put :choices
      end
    end

    resources :compositions do
      member do
        put :add_champion
        put :remove_champion
        put :ratio
      end
    end

    resources :team_applications do
      member do
        get :reject
        put :answer
      end
    end

    get 'recruitment_center' => 'team_applications#recruitment_center', as: "recruitment_center"

    resources :subscription_plans do
      member do
        put :select_duration
        get :informations
        put :payment
        get :payment_response
        get :payment_result
        get :restricted_content
      end
    end

    resources :subscriptions do
      member do
        post :renewal
        put :state
      end
    end

    resources :wallets do
      member do
        get :virtual_currency
        put :manager
        get :informations
        post :payment
        get :payment_response
        get :payment_result
      end
    end

    resources :discord do
      member do
        get :team_preview
      end
    end

    resources :achievements do
      member do
        put :add_user
      end
    end

    resources :seances do
      member do
        put :validate
      end
    end

    resources :mentorats do
      member do
        get :mentorat_preview
        put :change_teacher
        put :claim
        put :stop
      end
    end

    resources :premades do
      member do
        put :leave
        put :kick
      end
    end

    resources :invitations do
      member do
        get :generate_parrainage_link
        put :accept
        put :decline
      end
    end

    resources :friendships do
      member do
        put :accept
        put :decline
        put :remove
        put :block
        put :unblock
      end
    end

    resources :votes do
      member do
        put :election
      end
    end

    resources :teamings do
      member do
        put :swap
        put :swaper
        put :swap_captain
        put :advices_validation
      end
    end

    resources :notifications do
      member do
        put :mark_as_read
        get :mark_read
      end
    end

    devise_for :users, skip: :omniauth_callbacks, :controllers => { :registrations => "users/registrations" }

    devise_scope :user do
      get "sign_up", to: "devise/registrations#new"
      get '/users/:id/password/edit', to: "devise/passwords#edit", as: "reset_pw"
      put '/update_password', to: "devise/passwords#update", as: "update_pw"
      get '/registration/edit' => 'devise/registrations#edit'
      post "/registration/create" => "users/registrations#create", as: "create_user"
      get "/password/reset" => "devise/passwords#edit"
      get "login", to: "devise/sessions#new"
      get "logout", to: "devise/sessions#destroy"
    end

=begin
    devise_for :users, skip: :omniauth_callbacks, :controllers => { registrations: "registrations" } do
      get 'users/sign_up' => 'devise/registrations#new'
      #get '/users/edit' => 'devise/registrations#edit'
    end

    devise_scope :user do
     get "sign_up", to: "devise/registrations#new"
     get "login", to: "devise/sessions#new"
     get "logout", to: "devise/sessions#destroy"
   end
=end

    get 'dashboard' => 'users#dashboard'
    get 'second_step' => 'game_accounts#second_step'
    get 'third_step' => 'users#third_step'
    get 'searching_team' => 'users#searching_team'
    get 'leave_team' => 'users#leave_team'

    get 'subscription/manager' => 'subscriptions#manager', as: 'subscriptions_manager'

    get 'about' => 'home#about'
    get 'admin_panel' => 'home#admin_panel'
    get 'codename_fifty' => 'home#code'
    get 'analytics' => 'home#analytics'
    get 'parrainages' => 'users#parrainages'
    get 'join_us' => 'home#join_us'
    get 'our_partners' => 'home#our_partners', as: 'our_partners'
    get 'our_streamers' => 'home#our_streamers', as: 'our_streamers'
    get 'our_team' => 'home#our_team', as: 'our_team'
    get 'pricing' => 'home#pricing', as: 'pricing'
    get 'pantheon' => 'home#pantheon', as: 'pantheon'
    get 'profil'  => 'home#profil_user_type'
    get 'unsubscribe' => 'home#unsubscribe', as: 'unsubscribe'
    get 'eula' => 'legal#eula', as: 'eula'
    get 'cgu' => 'legal#cgu', as: 'cgu'

    scope '/wallets', :controller => :wallets do
      post :notification
    end

    get 'index.php/joueurs-lol' => 'home#old_page'
    get 'index.php/joueurs-ow' => 'home#old_page'
    get 'index.php' => 'home#old_page'
    get '/index.php/*path' => 'home#old_page'
    get '/components/*path' => 'home#old_page'
    get '/images/*path' => 'home#old_page'
    get '/administrator/*path' => 'home#old_page'
    get '/modules/*path' => 'home#old_page'

    get 'team_builder' => 'teams#team_builder'

    post 'analytics_search', :to => 'home#analytics_search', :as => 'analytics_search'

    get 'contact' => 'contacts#new'

    root to: "home#index"

  end

  get '/:short_url', to: 'urls#show'

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  has_one :account, through: :user, :class_name => "GameAccount"
  belongs_to :subscription_plan

  DURATION = {"1 mois" => 1, "3 mois (-5%)" => 3, "6 mois (-10%)" => 6, "12 mois (2 mois gratuits)" => 12}.freeze

  self.per_page = 20
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :check_privileges!
  before_action :set_subscription, only: [:state, :destroy]
  before_action :set_subscriptions, only: [:index, :state, :destroy]

  def index
    authorize! :manage, :all
    respond_to do |format|
      format.html
      format.js
    end
  end

  def manager
    @subscription = current_user.active_subscription
    @subscriptions = current_user.subscriptions.where.not(active:nil)
  end

  def create
    @user = current_user
    @plan = SubscriptionPlan.find(params[:plan])
    @end_date = (Time.now.tomorrow + params[:duration].to_i.months).to_date unless params[:duration].nil?
    @price = params[:price].to_f.round(2)
    @subscription = Subscription.find_or_create_by(user: @user, subscription_plan: @plan, end_date: @end_date, price: @price, active: nil)
    redirect_to informations_subscription_plan_path(@plan, subscription: @subscription.id)
  end

  def renewal
    @user = current_user
    @subscription = @user.active_subscription
    @subscription.renewal_price = params[:price].to_f.round(2)
    @subscription.renewal_duration = params[:duration].to_i
    @subscription.save
    redirect_to informations_subscription_plan_path(@subscription.subscription_plan, subscription: @subscription.id)
  end

  def state
    Subscription.transaction do
      @user = @subscription.user
      unless @subscription.end_date < Time.now
        unless @user.can? :manage, :all
          if @subscription.active == true
            @subscription.active = false
            @user.role = "standard"
          elsif @subscription.active == false
            @subscription.active = true
            @user.role = @subscription.subscription_plan.role
          else
            @subscription.active = true
            @user.role = @subscription.subscription_plan.role
          end
          @subscription.save!
          @user.save!
          respond_to do |format|
            format.html { redirect_to subscriptions_path, notice: "Etat de l'abonnement mis a jour." }
            format.js
          end
        end
      else
        redirect_to subscriptions_path, alert: "Cet abonnement est expiré."
      end
    end
  end

  def destroy
    Subscription.transaction do
      @user = @subscription.user
      if @user.role == @subscription.subscription_plan.role
        @user.role = "standard"
        @user.save!
      end
      @subscription.destroy!
      respond_to do |format|
        format.html { redirect_to subscriptions_path, notice:"Abonnement supprimé avec succès" }
        format.js
      end
    end
  end

  private

  def set_subscription
    @subscription = Subscription.find(params[:id])
  end

  def set_subscriptions
    @search = Subscription.joins(:account).search(params[:q])
    @subscriptions = @search.result.paginate(:page => params[:page])
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Joueur</th>
      <th><%= sort_link @search, :subscription_plan_id, "Formule", {}, { :remote => true, :method => :get } %></th>
      <th><%= sort_link @search, :created_at, "Début", {}, { :remote => true, :method => :get } %></th>
      <th><%= sort_link @search, :end_date, "Fin", {}, { :remote => true, :method => :get } %></th>
      <th>Durée</th>
      <th><%= sort_link @search, :price, "Prix", {}, { :remote => true, :method => :get } %></th>
      <th><%= sort_link @search, :payment_method, "Paiement", {}, { :remote => true, :method => :get } %></th>
      <th><%= sort_link @search, :active, "Etat", {}, { :remote => true, :method => :get } %></th>
    </tr>
  </thead>
  <tbody>
    <% @subscriptions.order('created_at desc').each do |subscription| %>
    <tr>
      <td><%= link_to subscription.user.account.name, user_preview_user_path(id: subscription.user_id), method: :get, remote: true %></td>
      <td><%= subscription.subscription_plan.title %></td>
      <td><%= subscription.created_at.strftime("%d/%m/%y") %></td>
      <td>
        <% if subscription.end_date.present? %>
          <%= subscription.end_date.strftime("%d/%m/%y") %>
        <% else %>
          A vie
        <% end %>
      </td>
      <td>
        <% if subscription.end_date.present? %>
          <%= (subscription.end_date.year * 12 + subscription.end_date.month) - (subscription.created_at.year * 12 + subscription.created_at.month) %> mois
        <% else %>
          Illimité
        <% end %>
      </td>
      <td>
        <% if subscription.price < 700 %>
          <%= subscription.price.to_f.round(2) %>€
        <% else %>
          <%= subscription.price.to_i %> <i class="ra ra-gem" style="color:#3498db;"></i>
        <% end %>
      </td>
      <td><%= subscription.payment_method.capitalize unless subscription.payment_method.nil? %></td>
      <td>
        <%= link_to state_subscription_path(subscription), method: :put, remote: true do %>
          <% if subscription.active == true %>
          Actif
          <% elsif subscription.active == false %>
          Inactif
          <% else %>
          Attente
          <% end %>
        <% end %>
      </td>
      <td><%= link_to '<i class="fa fa-remove" aria-hidden="true"></i>'.html_safe, subscription, method: :delete, data: { confirm: 'Etes-vous sûr ?' }, remote: true %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/subscriptions/_pagination.html.erb
<%= will_paginate @subscriptions, :previous_label => "Précédent", :next_label => "Suivant", inner_window: 2, outer_window: 1 %>

app/views/subscriptions/destroy.js.erb
$('#index').html("<%= j (render 'subscriptions/index') %>");

app/views/subscriptions/index.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Abonnements</h3>
    </div>
    <div class="panel-body">
      <%= search_form_for @search, url: subscriptions_path, method: :get, remote: true do |f| %>
      <div id="subscription-search-form" class="panel panel-default" style="padding:5px 30px;position:relative;margin:0 auto;">
        <div class="row">
            <div class="col-xs-3">
              <%= f.search_field :account_name_cont, placeholder:"Joueur", class:"form-control" %>
            </div>
            <div class="col-xs-5" style="padding-top:5px;">
              <%= f.select :subscription_plan_id_eq, options_from_collection_for_select(SubscriptionPlan.all, :id, :title, @search.subscription_plan_id_eq), prompt:"-- Plan --" %>
              <%= f.select :active_eq, {"Actif" => true, "Inactif" => false}, prompt:"-- Etat --" %>
              <%= f.select :payment_method_eq, {"Paypal" => "paypal", "Gems" => "gems"}, prompt:"-- Paiement --" %>
            </div>
            <div class="col-xs-4 text-right" style="padding-top:5px;">
              <%= f.submit %>
              <%= link_to "Reset", subscriptions_path, class:"btn btn-basic", style:"margin-left:5px;" %>
            </div>
        </div>
      </div>
      <% end %>
      <hr>
      <div id="index">
        <%= render 'subscriptions/index' %>
      </div>
    </div>
    <div class="panel-footer">
      <div class="row">
        <div class="col-sm-3" style="padding-top:10px;">
          <%= link_to "Retour", admin_panel_path, class:"btn btn-default" %>
        </div>
        <div id="subscriptions-paginate" class="col-sm-6 text-center">
          <%= render 'subscriptions/pagination' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/subscriptions/index.js.erb
$('#index').html("<%= j (render 'subscriptions/index') %>");
$('#subscriptions-paginate').html("<%= j (render 'subscriptions/pagination') %>");

app/views/subscriptions/manager.html.erb
<style type="text/css">
  #my-subscription tbody tr:first-child td { border-top: 0 }
</style>
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3><%=t 'subscriptions.manager_title' %></h3>
    </div>
    <div class="panel-body" style="padding:50px 15px;">
      <div class="row">
        <div class="col-sm-6">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <h4><%=t 'subscriptions.mine' %></h4>
            </div>
            <div class="panel-body" style="height:200px;">
              <% unless @subscription.nil? %>
                <table id="my-subscription" class="table">
                  <tbody>
                    <tr>
                      <td><h5><%=t 'subscriptions.formula' %></h5></td>
                      <td><%= @subscription.subscription_plan.title %></td>
                    </tr>
                    <tr>
                      <td><h5><%=t 'subscriptions.duration' %></h5></td>
                      <td>
                        <% unless @subscription.end_date.nil? %>
                          <%=t 'layout.from_to_date', date1: @subscription.created_at.strftime("%d/%m/%y"), date2: @subscription.end_date.strftime("%d/%m/%y") %>
                        <% else %>
                          <%=t 'subscriptions.lifetime' %>
                        <% end %>
                      </td>
                    </tr>
                    <tr>
                      <td><h5><%=t 'subscriptions.remaining' %></h5></td>
                      <td>
                        <%  unless @subscription.end_date.nil? %>
                          <%= (@subscription.end_date.to_date - Time.now.to_date).to_i %> <%=t 'layout.days' %>
                        <% else %>
                          <%=t 'subscriptions.unlimited' %>
                        <% end %>
                      </td>
                    </tr>
                  </tbody>
                </table>
              <% else %>
                <p style="text-align:center;margin-top:80px;"><%=t 'subscriptions.none' %></p>
              <% end %>
            </div>
            <div class="panel-footer">
              <% unless @subscription.nil? %>
                <% unless @subscription.end_date.nil? %>
                  <%= link_to "#{t 'subscriptions.renew'}", subscription_plan_path(@subscription.subscription_plan), class:"btn btn-primary btn-block" %>
                <% else %>
                  <br>
                <% end %>
              <% else %>
                <%= link_to "#{t 'layout.become_premium'}", pricing_path, class:"btn btn-primary btn-block" %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <h4><%=t 'subscriptions.history' %></h4>
            </div>
            <div class="panel-body" style="height:260px;width:100%;overflow-x:hidden;overflow-y:scroll;">
              <table class="table" style="width:100%;">
                <thead>
                  <tr>
                    <th><%=t 'subscriptions.formula' %></th>
                    <th><%=t 'layout.start' %></th>
                    <th><%=t 'layout.end' %></th>
                    <th><%=t 'subscriptions.price' %></th>
                  </tr>
                </thead>
                <tbody>
                  <% @subscriptions.each do |subscription| %>
                    <tr>
                      <td><%= subscription.subscription_plan.title %></td>
                      <td><%= subscription.created_at.strftime("%d/%m/%y") %></td>
                      <td>
                        <% unless subscription.end_date.nil? %>
                          <%= subscription.end_date.strftime("%d/%m/%y") %>
                        <% else %>
                          <%=t 'subscriptions.lifetime' %>
                        <% end %>
                      </td>
                      <td>
                        <% if subscription.price < 700 %>
                          <%= subscription.price.to_f.round(2) %>€
                        <% else %>
                          <%= subscription.price.to_i %> <i class="ra ra-gem" style="color:#3498db;"></i>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      <%= link_to "#{t 'btn.back'}", dashboard_path, class:"btn btn-default" %>
    </div>
  </div> <!-- Panel -->
</div>

app/views/subscriptions/state.js.erb
$('#index').html("<%= j (render 'subscriptions/index') %>");